// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.6.1
// source: grpcurlshorter/proto/urlshorter.proto

package urlshorter

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LongUrl struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Long string `protobuf:"bytes,1,opt,name=long,proto3" json:"long,omitempty"`
}

func (x *LongUrl) Reset() {
	*x = LongUrl{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpcurlshorter_proto_urlshorter_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LongUrl) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LongUrl) ProtoMessage() {}

func (x *LongUrl) ProtoReflect() protoreflect.Message {
	mi := &file_grpcurlshorter_proto_urlshorter_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LongUrl.ProtoReflect.Descriptor instead.
func (*LongUrl) Descriptor() ([]byte, []int) {
	return file_grpcurlshorter_proto_urlshorter_proto_rawDescGZIP(), []int{0}
}

func (x *LongUrl) GetLong() string {
	if x != nil {
		return x.Long
	}
	return ""
}

type ShortUrl struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Short string `protobuf:"bytes,1,opt,name=short,proto3" json:"short,omitempty"`
}

func (x *ShortUrl) Reset() {
	*x = ShortUrl{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpcurlshorter_proto_urlshorter_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShortUrl) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShortUrl) ProtoMessage() {}

func (x *ShortUrl) ProtoReflect() protoreflect.Message {
	mi := &file_grpcurlshorter_proto_urlshorter_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShortUrl.ProtoReflect.Descriptor instead.
func (*ShortUrl) Descriptor() ([]byte, []int) {
	return file_grpcurlshorter_proto_urlshorter_proto_rawDescGZIP(), []int{1}
}

func (x *ShortUrl) GetShort() string {
	if x != nil {
		return x.Short
	}
	return ""
}

var File_grpcurlshorter_proto_urlshorter_proto protoreflect.FileDescriptor

var file_grpcurlshorter_proto_urlshorter_proto_rawDesc = []byte{
	0x0a, 0x25, 0x67, 0x72, 0x70, 0x63, 0x75, 0x72, 0x6c, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x72,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x75, 0x72, 0x6c, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x65,
	0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x75, 0x72, 0x6c, 0x73, 0x68, 0x6f, 0x72,
	0x74, 0x65, 0x72, 0x22, 0x1d, 0x0a, 0x07, 0x4c, 0x6f, 0x6e, 0x67, 0x55, 0x72, 0x6c, 0x12, 0x12,
	0x0a, 0x04, 0x6c, 0x6f, 0x6e, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6c, 0x6f,
	0x6e, 0x67, 0x22, 0x20, 0x0a, 0x08, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x55, 0x72, 0x6c, 0x12, 0x14,
	0x0a, 0x05, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x73,
	0x68, 0x6f, 0x72, 0x74, 0x32, 0x77, 0x0a, 0x0a, 0x75, 0x72, 0x6c, 0x75, 0x68, 0x6f, 0x72, 0x74,
	0x65, 0x72, 0x12, 0x35, 0x0a, 0x06, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x12, 0x13, 0x2e, 0x75,
	0x72, 0x6c, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x72, 0x2e, 0x4c, 0x6f, 0x6e, 0x67, 0x55, 0x72,
	0x6c, 0x1a, 0x14, 0x2e, 0x75, 0x72, 0x6c, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x72, 0x2e, 0x53,
	0x68, 0x6f, 0x72, 0x74, 0x55, 0x72, 0x6c, 0x22, 0x00, 0x12, 0x32, 0x0a, 0x03, 0x47, 0x65, 0x74,
	0x12, 0x14, 0x2e, 0x75, 0x72, 0x6c, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x72, 0x2e, 0x53, 0x68,
	0x6f, 0x72, 0x74, 0x55, 0x72, 0x6c, 0x1a, 0x13, 0x2e, 0x75, 0x72, 0x6c, 0x73, 0x68, 0x6f, 0x72,
	0x74, 0x65, 0x72, 0x2e, 0x4c, 0x6f, 0x6e, 0x67, 0x55, 0x72, 0x6c, 0x22, 0x00, 0x42, 0x12, 0x5a,
	0x10, 0x2e, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x75, 0x72, 0x6c, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x65,
	0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_grpcurlshorter_proto_urlshorter_proto_rawDescOnce sync.Once
	file_grpcurlshorter_proto_urlshorter_proto_rawDescData = file_grpcurlshorter_proto_urlshorter_proto_rawDesc
)

func file_grpcurlshorter_proto_urlshorter_proto_rawDescGZIP() []byte {
	file_grpcurlshorter_proto_urlshorter_proto_rawDescOnce.Do(func() {
		file_grpcurlshorter_proto_urlshorter_proto_rawDescData = protoimpl.X.CompressGZIP(file_grpcurlshorter_proto_urlshorter_proto_rawDescData)
	})
	return file_grpcurlshorter_proto_urlshorter_proto_rawDescData
}

var file_grpcurlshorter_proto_urlshorter_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_grpcurlshorter_proto_urlshorter_proto_goTypes = []interface{}{
	(*LongUrl)(nil),  // 0: urlshorter.LongUrl
	(*ShortUrl)(nil), // 1: urlshorter.ShortUrl
}
var file_grpcurlshorter_proto_urlshorter_proto_depIdxs = []int32{
	0, // 0: urlshorter.urluhorter.Create:input_type -> urlshorter.LongUrl
	1, // 1: urlshorter.urluhorter.Get:input_type -> urlshorter.ShortUrl
	1, // 2: urlshorter.urluhorter.Create:output_type -> urlshorter.ShortUrl
	0, // 3: urlshorter.urluhorter.Get:output_type -> urlshorter.LongUrl
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_grpcurlshorter_proto_urlshorter_proto_init() }
func file_grpcurlshorter_proto_urlshorter_proto_init() {
	if File_grpcurlshorter_proto_urlshorter_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_grpcurlshorter_proto_urlshorter_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LongUrl); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpcurlshorter_proto_urlshorter_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ShortUrl); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_grpcurlshorter_proto_urlshorter_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_grpcurlshorter_proto_urlshorter_proto_goTypes,
		DependencyIndexes: file_grpcurlshorter_proto_urlshorter_proto_depIdxs,
		MessageInfos:      file_grpcurlshorter_proto_urlshorter_proto_msgTypes,
	}.Build()
	File_grpcurlshorter_proto_urlshorter_proto = out.File
	file_grpcurlshorter_proto_urlshorter_proto_rawDesc = nil
	file_grpcurlshorter_proto_urlshorter_proto_goTypes = nil
	file_grpcurlshorter_proto_urlshorter_proto_depIdxs = nil
}
